import Mock from '@shared/assets/metaMask.png';
export const bidsMock = [
  {
    id: 32679,
    offerType: 'sell',
    lotType: 'SAFT',
    isHot: false,
    publishedAt: new Date(),
    fdv: 122354,
    offerMaker: 'Some user',
    offerMakerIcon: <Mock />,
    isDirectSeller: true,
    location: 'Russia',
    lotName: 'USDT',
    lotIconName: 'UsdtIcon',
    status: 'draft',
    bidSize: 123,
  },
  {
    id: 32680,
    offerType: 'buy',
    lotType: 'SAFT',
    isHot: false,
    publishedAt: new Date(),
    fdv: 122354,
    offerMaker: 'Some user',
    offerMakerIcon: <Mock />,
    isDirectSeller: true,
    location: 'Germany',
    lotName: 'USDT',
    lotIconName: 'UsdtIcon',
    status: 'draft',
    bidSize: 145,
  },
  {
    id: 32681,
    offerType: 'sell',
    lotType: 'SAFT',
    isHot: false,
    publishedAt: new Date(),
    fdv: 101120,
    offerMaker: 'Some user',
    offerMakerIcon: <Mock />,
    isDirectSeller: true,
    location: 'Rome',
    lotName: 'USDT',
    lotIconName: 'UsdtIcon',
    status: 'draft',
    bidSize: 421,
  },
  {
    id: 32682,
    offerType: 'buy',
    lotType: 'SAFT',
    isHot: false,
    publishedAt: new Date(),
    fdv: 101120,
    offerMaker: 'Some user',
    offerMakerIcon: <Mock />,
    isDirectSeller: true,
    location: 'Canada',
    lotName: 'USDT',
    lotIconName: 'UsdtIcon',
    status: 'draft',
    bidSize: 324,
  },
  {
    id: 32683,
    offerType: 'buy',
    lotType: 'SAFT',
    isHot: false,
    publishedAt: new Date(),
    fdv: 101120,
    offerMaker: 'Some user',
    offerMakerIcon: <Mock />,
    isDirectSeller: true,
    location: 'Brazil',
    lotName: 'USDT',
    lotIconName: 'UsdtIcon',
    status: 'draft',
    bidSize: 129,
  },
];
