import * as yup from 'yup';

import {
  COMMON_BID_MAKER_TYPES_INPUT,
  COMMON_DEADLINE_INPUT,
  COMMON_DIRECTION_INPUT,
  COMMON_MEDIATOR_INPUT,
  COMMON_MIN_FILTER_SUMMARY_INPUT,
  COMMON_MIN_FILTER_UNITS_INPUT,
  COMMON_OFFER_MAKER_TYPES_INPUT,
  COMMON_PRICE_INPUT,
  COMMON_SUMMARY_INPUT,
  COMMON_TELEGRAM_INPUT,
  COMMON_UNITS_INPUT,
  COMMON_PERMANENT_INPUT,
} from '../inputs';

export const CommonInputs = yup.object({
  COMMON_BID_MAKER_TYPES_INPUT: COMMON_BID_MAKER_TYPES_INPUT.required(),
  COMMON_DEADLINE_INPUT: COMMON_DEADLINE_INPUT.when('COMMON_PERMANENT_INPUT', {
    is: true,
    then: (field) => field.notRequired(),
    otherwise: (field) => field.required(),
  }),
  COMMON_DIRECTION_INPUT: COMMON_DIRECTION_INPUT.required().default('BUY'),
  COMMON_MEDIATOR_INPUT: COMMON_MEDIATOR_INPUT.required(),
  COMMON_MIN_FILTER_SUMMARY_INPUT,
  COMMON_MIN_FILTER_UNITS_INPUT,
  COMMON_OFFER_MAKER_TYPES_INPUT: COMMON_OFFER_MAKER_TYPES_INPUT.required(),
  COMMON_PRICE_INPUT,
  COMMON_SUMMARY_INPUT,
  COMMON_TELEGRAM_INPUT: COMMON_TELEGRAM_INPUT.required(),
  COMMON_UNITS_INPUT,
  COMMON_PERMANENT_INPUT,
});

export type CommonInputsModel = yup.InferType<typeof CommonInputs>;
