import * as yup from 'yup';

import {
  INVEST_DOC_ASSET_CREATE_REQUEST_INPUT,
  INVEST_DOC_ASSET_PK_INPUT,
  INVEST_DOC_FDV_INPUT,
  INVEST_DOC_ROUND_FDV_INPUT,
  INVEST_DOC_ROUND_PRICE_INPUT,
  INVEST_DOC_ROUND_SHARE_INPUT,
  INVEST_DOC_ROUND_SUMMARY_INPUT,
  INVEST_DOC_ROUND_TYPE_INPUT,
  INVEST_DOC_ROUND_UNITS_INPUT,
  INVEST_DOC_SHARE_INPUT,
  INVEST_DOC_WITH_REASSIGN_INPUT,
} from '../inputs';

export const InvestDocInputs = yup.object({
  INVEST_DOC_ASSET_PK_INPUT: INVEST_DOC_ASSET_PK_INPUT.required(),
  INVEST_DOC_ASSET_CREATE_REQUEST_INPUT,
  INVEST_DOC_FDV_INPUT: INVEST_DOC_FDV_INPUT.required(),
  INVEST_DOC_SHARE_INPUT,
  INVEST_DOC_WITH_REASSIGN_INPUT,
});

export type InvestDocModel = yup.InferType<typeof InvestDocInputs>;

export const InvestDocRoundInputs = yup.object({
  INVEST_DOC_ROUND_FDV_INPUT,
  INVEST_DOC_ROUND_PRICE_INPUT,
  INVEST_DOC_ROUND_SHARE_INPUT,
  INVEST_DOC_ROUND_SUMMARY_INPUT,
  INVEST_DOC_ROUND_TYPE_INPUT,
  INVEST_DOC_ROUND_UNITS_INPUT,
});

export type InvestDocRoundModel = yup.InferType<typeof InvestDocRoundInputs>;
