export const KeyResultType = [
  'TELEGRAM_CHAT',
  'OFFER_MAKER_VALIDATION',
  'BID_MAKER_VALIDATION',
  'AGENT_VALIDATION',
  'KYC_VALIDATION',
  'AML_VALIDATION',
  'KYB_VALIDATION',
  'DOCUMENT_OWNERSHIP',
  'DOCUMENT_RESIGNED',
  'TRANSACTION_PAYMENT',
  'MARSBASE_COMMISSION',
  'AGENT_COMMISSION',
] as const;
export type KeyResultType = (typeof KeyResultType)[number];
