export const SYMBOL_SERVICE_NAME = Symbol('SYMBOL_SERVICE_NAME');
export const SYMBOL_SERVICE_DEBUG = Symbol('SYMBOL_SERVICE_DEBUG');
export const SYMBOL_SERVICE_ON_ERROR = Symbol('SYMBOL_SERVICE_ON_ERROR');
export const SYMBOL_SERVICE_IS_STARTED = Symbol('SYMBOL_SERVICE_IS_STARTED');
