name: Build and Deploy

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Echo Env
        run: echo "${{ secrets.KUBERNETES_CLUSTER_NAME }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.KUBERNETES_CLUSTER_NAME }}

      - name: Build container image
        run: docker buildx build --cache-to type=gha --cache-from type=gha -t registry.digitalocean.com/marsbase/frontend:$(echo $GITHUB_SHA | head -c7) \
          --file ./docker/Dockerfile --push ./

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl set image deployment/frontend "frontend=registry.digitalocean.com/marsbase/frontend:$(echo $GITHUB_SHA | head -c7)"

      - name: Verify deployment
        run: kubectl rollout status deployment/frontend
